
activate_redshift:
  name: Activate redshift
  description: Activates the redshift.

deactivate_redshift:
  name: Deactivate redshift
  description: Deactivates the redshift optionally and sets all lights to a given temperature.
  fields:
    color_temp:
      name: Manual color temperature (Kelvin)
      description: Color temperature for the lights in Kelvin.
      advanced: true
      selector:
        number:
          min: 2000
          max: 6500
          step: 100
          unit_of_measurement: K

activate_brightness:
  name: Activate brightness
  description: Activates the brightness.

deactivate_brightness:
  name: Deactivate brightness
  description: Deactivates the brightness optionally and sets all lights to a given brightness.
  fields:
    brightness:
      name: Manual brightness
      description: Brightness for the lights.
      advanced: true
      selector:
        number:
          min: 0
          max: 255
          step: 10

dont_touch:
  name: Don't touch
  description: Don't manipulate given lights.
  target:
    entity:
      domain: light

handle_again:
  name: Handle again
  description: Again manipulate given lights.
  target:
    entity:
      domain: light
